### ISSUE TITLE
Text Rendering

### ISSUE THREAD

**Issue by RobLoach** [RobLoach/pntr#9]
- bitmap fonts
- ttf

**Comment by konsumer** [comment]
I started working on a seperate header with [libschrift](https://github.com/tomolt/libschrift) that can do ttf + otf fonts.

For bitmap fonts maybe another header could be for that, so the user can just import what they need for their thing, since bitmap fonts are essentially tilemaps, with some text-oriented helpers.

I was thinking these functions would be enough to do just about anything:

```c
# load a font
pntr_font* font =  pntr_load_font("cool.ttf", size);

# create an image that can be drawn, that wraps text to the width
pntr_image* ti = pntr_text_create("Hello", font, width, height, color);

# get the size of text without drawing it
pntr_rect* td = pntr_text_dimensions("Hello", font, wrapWidth);
```

**Comment by RobLoach** [comment]
Woooooo https://github.com/RobLoach/pntr/commit/5c7dc82c7ba583cbadadfd11ed6ca7e6bf9ec0d0

``` c
pntr_font* font = pntr_load_bmfont("font.png", "abc");
pntr_draw_text(dst, font, "aaaaaaa", 10, 10);
pntr_unload_font(font);
```

If we get TTF if there, we could have it be...
``` c
pntr_load_ttf()
```

... and then a method to handle all instances with `pntr_load_font()`.

**Comment by RobLoach** [comment]
Made issues for some othe font formats
